{{ if and (.Values.useCrdConfig) (not ( .Capabilities.APIVersions.Has "ext.appd.com/v1/AppDynamicsInstrumentation")) }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: appdynamicsinstrumentations.ext.appd.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ext.appd.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                exclude:
                  type: array
                  items:
                    type: object
                    properties:
                      api:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                      nameRegex:
                        type: string
                include:
                  type: array
                  items:
                    type: object
                    properties:
                      api:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                      nameRegex:
                        type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: appdynamicsinstrumentations
    # singular name to be used as an alias on the CLI and for display
    singular: appdynamicsinstrumentation
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AppDynamicsInstrumentation
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - adi
    - adis

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceaccount }}-crd
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "ext.appd.com"
    resources:
      - "*"
    verbs:
      - "*"


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceaccount }}-crd
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccount }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceaccount }}-crd
  apiGroup: rbac.authorization.k8s.io
{{ end }}