apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceaccount }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - ext.appd.com
    resources:
      - globalinstrumentation
      - instrumentation
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
