kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceaccount }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccount }}
roleRef:
  kind: Role
  name: {{ .Values.serviceaccount }}
  apiGroup: rbac.authorization.k8s.io