apiVersion: v1
kind: Pod
metadata:
  annotations:
    APPD_INSTRUMENTATION_VIA_RULE: demo/dotnetcore-instrumentation
    test: testval
  labels:
    app: myfirstapp
    appdApp: MD-instr-wh
    instrument: crd
    language: dotnetcore
  name: dotnetapp
spec:
  containers:
  - env:
    - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
      value: "<<APPD_ACCESS_KEY>>"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: "<<APPD_CONTROLLER>>"
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "<<APPD_CONTROLLER_PORT>>"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: "<<APPD_ACCOUNT>>"
    - name: LD_LIBRARY_PATH
      value: /opt/appdynamics-dotnetcore
    - name: CORECLR_PROFILER
      value: '{57e1aa68-2229-41aa-9931-a6e93bbc64d8}'
    - name: CORECLR_PROFILER_PATH
      value: /opt/appdynamics-dotnetcore/libappdprofiler.so
    - name: CORECLR_ENABLE_PROFILING
      value: "1"
    - name: APPDYNAMICS_AGENT_REUSE_NODE_NAME
      value: "true"
    - name: APPDYNAMICS_AGENT_APPLICATION_NAME
      value: MD-instr-wh
    - name: APPDYNAMICS_AGENT_TIER_NAME
      value: dotnetapp
    - name: APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX
      value: dotnetapp
    - name: APPDYNAMICS_NETVIZ_AGENT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: APPDYNAMICS_NETVIZ_AGENT_PORT
      value: "3892"
    image: chrlic/sample-dotnet-app:latest
    imagePullPolicy: Always
    name: myfirstapp
    ports:
    - containerPort: 7032
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: 250m
        memory: 100Mi
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: "~.*"
      readOnly: true
    - mountPath: /opt/appdynamics-dotnetcore
      name: appd-agent-repo-dotnetcore
  initContainers:
  - command:
    - cp
    - -r
    - /opt/appdynamics/.
    - /opt/appdynamics-dotnetcore
    image: appdynamics/dotnet-core-agent:latest
    imagePullPolicy: Always
    name: appd-agent-attach-dotnetcore
    resources:
      limits:
        cpu: 200m
        memory: 75M
      requests:
        cpu: 100m
        memory: 50M
    volumeMounts:
    - mountPath: /opt/appdynamics-dotnetcore
      name: appd-agent-repo-dotnetcore
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: "~.*"
      readOnly: true
  volumes:
  - name: "~kube-api-access-.*"
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - emptyDir: {}
    name: appd-agent-repo-dotnetcore

