
apiVersion: v1
kind: Pod
metadata:
  name: dotnetapp
  annotations:
    test: testval
  labels:
    app: myfirstapp
    appdApp: MD-instr-wh
    appdInstr: do
    language: dotnetcore
spec:
  containers:
  - name: myfirstapp
    image: chrlic/sample-dotnet-app:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 7032
    env:
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: 250m
        memory: 100Mi
