
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirstapp
  template:
    metadata:
      annotations:
        test: testval
      labels:
        app: myfirstapp
        appdApp: MD-instr-wh
        appdInstr: do
        language: dotnetcore
    spec:
      containers:
      - name: myfirstapp
        image: chrlic/sample-dotnet-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7032
        env:
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://otel-coll-deployment-hybrid-agent-default.wht.svc.cluster.local:4318
        - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
          value: http/protobuf
        - name: OTEL_DOTNET_AUTO_LOAD_TRACER_AT_STARTUP
          value: "true"
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 100Mi
---

apiVersion: v1
kind: Service
metadata:
  name: myfirstapp
  labels:
    run: myfirstapp
spec:
  ports:
  - port: 8484
    targetPort: 7032
    protocol: TCP
  selector:
    app: myfirstapp
  type: LoadBalancer
