images:
	curl https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar -o otel-java/opentelemetry-javaagent.jar
	curl https://github.com/cisco-open/otel-java/releases/latest/download/cisco-telescope-javaagent.jar -o cisco-telescope-java/cisco-telescope-javaagent.jar
	