apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceaccount }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      # - secrets
      - pods
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ext.appd.com
    resources:
      - clusterinstrumentations
      - instrumentations
      - opentelemetrycollectors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
