---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appd-aac
rules:
- apiGroups:
  - ext.appd.com
  resources:
  - ClusterInstrumentation
  - instrumentation
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
