
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: r
  name: testserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testserver
  template:
    metadata:
      annotations:
        test: testval
      labels:
        app: testserver
        appdApp: MD-instr-wh
        appdInstr: do
        language: nodejs
        # language: uni
    spec:
      containers:
      - name: testserver
        image: chrlic/sample-nodejs-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 100Mi
        env:
        - name: TEST_ENV1
          value: fff
        - name: TEST_ENV2
          value: |
            ahoj:
              veslo: dvevesla
        - name: TEST_ENV3
          value: ggg

---

apiVersion: v1
kind: Service
metadata:
  namespace: r
  name: testserver
  labels:
    run: testserver
spec:
  ports:
  - port: 8585
    targetPort: 8000
    protocol: TCP
  selector:
    app: testserver
  type: LoadBalancer
