apiVersion: v1
kind: Pod
metadata:
  annotations:
    APPD_INSTRUMENTATION_VIA_RULE: ~test-.*/java-instrumentation
    annot1: my-annotation
  labels:
    app: vendors
    appdApp: MD-Hybrid-App
    language: java
    otel: appd
  name: javatest
spec:
  containers:
  - env:
    - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
      value: "<<APPD_ACCESS_KEY>>"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: "<<APPD_CONTROLLER>>"
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "<<APPD_CONTROLLER_PORT>>"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: "<<APPD_ACCOUNT>>"
    - name: K8S_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: K8S_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: K8S_NAMESPACE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: k8s.pod.ip=$(K8S_POD_IP),k8s.pod.name=$(K8S_POD_NAME),k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.container.name=vendors,k8s.container.restart_count=0
    - name: _JAVA_OPTIONS
      value: '~ -Dappdynamics.agent.accountAccessKey=\$\(APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY\) 
        -Dappdynamics.agent.reuse.nodeName=true -Dappdynamics.socket.collection.bci.enable=true 
        -javaagent:/opt/appdynamics-java/javaagent.jar  -Dappdynamics.opentelemetry.enabled=true 
        -Dotel.resource.attributes=service.name=javatest,service.namespace=test-.*,\$\(OTEL_RESOURCE_ATTRIBUTES\) 
        -Dotel.traces.exporter=otlp,logging -Dotel.exporter.otlp.traces.endpoint=http://otel-collector-test.test-.*.svc.cluster.local:4317 '
    - name: APPDYNAMICS_AGENT_APPLICATION_NAME
      value: ~test-.*
    - name: APPDYNAMICS_AGENT_TIER_NAME
      value: javatest
    - name: APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX
      value: javatest
    - name: APPDYNAMICS_NETVIZ_AGENT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: APPDYNAMICS_NETVIZ_AGENT_PORT
      value: "3892"
    image: chrlic/echoapp:latest
    imagePullPolicy: Always
    name: vendors
    ports:
    - containerPort: 8181
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: 250m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: ~kube-api-access-.*
      readOnly: true
    - mountPath: /opt/appdynamics-java
      name: appd-agent-repo-java
  initContainers:
  - args:
    - cp -ar /opt/appdynamics/. /opt/appdynamics-java
    command:
    - /bin/sh
    - -c
    image: appdynamics/java-agent:latest
    name: appd-agent-attach-java
    resources:
      limits:
        cpu: 200m
        memory: 75M
      requests:
        cpu: 100m
        memory: 50M
    volumeMounts:
    - mountPath: /opt/appdynamics-java
      name: appd-agent-repo-java
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: ~kube-api-access-.*
      readOnly: true
  volumes:
  - name: ~kube-api-access-.*
    projected:
      sources:
      - serviceAccountToken:
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - emptyDir: {}
    name: appd-agent-repo-java
